// Prints the 10 additive Caddy reverse_proxy blocks for the test-deploy pool
// (external HTTPS 7444..7453 -> loopback 3774..3783). Reuses the existing
// self-signed cert pair shared across the prod blocks (SAN = IP).
//
// This script ONLY prints to stdout. Appending to /etc/caddy/Caddyfile and
// reloading caddy is a one-time, user-approved privileged step (see AGENTS.md
// "Local Test-Deployment Standard" and the framework spec §a):
//
//   sudo cp /etc/caddy/Caddyfile /etc/caddy/Caddyfile.bak.$(date +%s)
//   node scripts/test-deploy-caddy.ts | sudo tee -a /etc/caddy/Caddyfile >/dev/null
//   sudo caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
//   sudo systemctl reload caddy
//   # then open inbound TCP 7444-7453 in the OVH panel, and:
//   touch ~/.t3-test-deploy/caddy-bootstrapped

import {
  assertNotProd,
  externalPorts,
  HOST,
  loopbackForExternal,
  unitForExternal,
} from "./test-deploy-lib.ts";

const CERT = "/etc/caddy/t3code-server.crt";
const KEY = "/etc/caddy/t3code-server.key";

function blockFor(externalPort: number, loopbackPort: number): string {
  return `https://${HOST}:${externalPort} {
    tls ${CERT} ${KEY} {
        protocols tls1.2 tls1.3
    }
    encode gzip
    handle {
        reverse_proxy 127.0.0.1:${loopbackPort} {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
            header_up X-Real-IP {remote_host}
        }
    }
}`;
}

function main(): void {
  const blocks: string[] = [];
  blocks.push("# --- T3 Code local test-deploy pool (slots 0..9) ---");
  blocks.push("# Generated by scripts/test-deploy-caddy.ts. Additive only.");
  for (const externalPort of externalPorts()) {
    const loopbackPort = loopbackForExternal(externalPort);
    // Never emit a block for a prod target.
    assertNotProd(externalPort, loopbackPort, unitForExternal(externalPort));
    blocks.push(blockFor(externalPort, loopbackPort));
  }
  process.stdout.write(`${blocks.join("\n\n")}\n`);
}

main();
